[[Diamond]]
arch = "aarch64"
git-tree-sha1 = "4a5d492c74e81b6bc43081844e057c1ea15f1c55"
os = "macos"

    [[Diamond.download]]
    sha256 = "ac260cee7be9a6965316fb2107a9eabeb7a5057f96a57b720fd026be19d884cb"
    url = "https://github.com/JuliaBinaryWrappers/Diamond_jll.jl/releases/download/Diamond-v2.1.8+0/Diamond.v2.1.8.aarch64-apple-darwin.tar.gz"
[[Diamond]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ef990f7800902ef69ecf3003d1f53389dda0e974"
libc = "glibc"
os = "linux"

    [[Diamond.download]]
    sha256 = "36d2f10bd7e5c07fa165f02e0129877a516cdc00ba45f53e0080c2595749df40"
    url = "https://github.com/JuliaBinaryWrappers/Diamond_jll.jl/releases/download/Diamond-v2.1.8+0/Diamond.v2.1.8.aarch64-linux-gnu-cxx03.tar.gz"
[[Diamond]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "77a6dee195b8d7c451c934424953e6cb325eee37"
libc = "glibc"
os = "linux"

    [[Diamond.download]]
    sha256 = "208f23d0e36510429f5f6ee829fc0fd3861f3f4db749f82082037284f8d5558e"
    url = "https://github.com/JuliaBinaryWrappers/Diamond_jll.jl/releases/download/Diamond-v2.1.8+0/Diamond.v2.1.8.aarch64-linux-gnu-cxx11.tar.gz"
[[Diamond]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4371a2470fa7c6cbb4770ef4634b1da6e8d543a4"
libc = "musl"
os = "linux"

    [[Diamond.download]]
    sha256 = "7498825ebd7d0a49523114c541b0296760de575e7ca2bf95926b6d1177391ddf"
    url = "https://github.com/JuliaBinaryWrappers/Diamond_jll.jl/releases/download/Diamond-v2.1.8+0/Diamond.v2.1.8.aarch64-linux-musl-cxx03.tar.gz"
[[Diamond]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dba68a4d143e0ca82cade44010761088216173c0"
libc = "musl"
os = "linux"

    [[Diamond.download]]
    sha256 = "074d37c890e885188a9072b5796f51382fae6ac45ac927d79739f5579d394285"
    url = "https://github.com/JuliaBinaryWrappers/Diamond_jll.jl/releases/download/Diamond-v2.1.8+0/Diamond.v2.1.8.aarch64-linux-musl-cxx11.tar.gz"
[[Diamond]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0968b6da714cdc94c43985c42df15acb8352ef2e"
libc = "glibc"
os = "linux"

    [[Diamond.download]]
    sha256 = "8e67e984df60bb02f5fb268149d30d6fb7aab97c269af0ddbe36e06574f0741f"
    url = "https://github.com/JuliaBinaryWrappers/Diamond_jll.jl/releases/download/Diamond-v2.1.8+0/Diamond.v2.1.8.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Diamond]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fefeda8512828911be63313bd1d438c57a8746b2"
libc = "glibc"
os = "linux"

    [[Diamond.download]]
    sha256 = "2e5e9fa8bb5ccf9db947b1c3818e66ae03df95c9e7e3b09bda74db268446967c"
    url = "https://github.com/JuliaBinaryWrappers/Diamond_jll.jl/releases/download/Diamond-v2.1.8+0/Diamond.v2.1.8.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Diamond]]
arch = "x86_64"
git-tree-sha1 = "d65edad86e30334e9b5bece0667d1d33e61f6776"
os = "macos"

    [[Diamond.download]]
    sha256 = "7d49ecb5c8575dfd872f27b2705f9006782eec33747ac6a80fbe2f4ef687319c"
    url = "https://github.com/JuliaBinaryWrappers/Diamond_jll.jl/releases/download/Diamond-v2.1.8+0/Diamond.v2.1.8.x86_64-apple-darwin.tar.gz"
[[Diamond]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1d1c900e2320d602c8a6e06e45d082b2e2315a8e"
libc = "glibc"
os = "linux"

    [[Diamond.download]]
    sha256 = "c07be4004b0fd8f65a9a1e5fe1cd137f79bd16493557bbb0536248d1e1d1dab3"
    url = "https://github.com/JuliaBinaryWrappers/Diamond_jll.jl/releases/download/Diamond-v2.1.8+0/Diamond.v2.1.8.x86_64-linux-gnu-cxx03.tar.gz"
[[Diamond]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1191a4380fa642c4aed832c996d79c4e1ce98545"
libc = "glibc"
os = "linux"

    [[Diamond.download]]
    sha256 = "2beaeafe06654766c9c221014f41668f079dcb4ab87b2d4f1999910f19fc5fba"
    url = "https://github.com/JuliaBinaryWrappers/Diamond_jll.jl/releases/download/Diamond-v2.1.8+0/Diamond.v2.1.8.x86_64-linux-gnu-cxx11.tar.gz"
[[Diamond]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fcf0f369991ccf92ef77a3c5c1b80f85f74d4a52"
libc = "musl"
os = "linux"

    [[Diamond.download]]
    sha256 = "a6c889e6ae132d5c572ffcfaa711b7180ac8a14f552aa8b3e02d6ae2b7184d41"
    url = "https://github.com/JuliaBinaryWrappers/Diamond_jll.jl/releases/download/Diamond-v2.1.8+0/Diamond.v2.1.8.x86_64-linux-musl-cxx03.tar.gz"
[[Diamond]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3854009343627966538c46be84c52b582e508c98"
libc = "musl"
os = "linux"

    [[Diamond.download]]
    sha256 = "4c40e02ed91abbf26349c7ab6aee4187b23ad49c2253478304f3e0ab50ea5371"
    url = "https://github.com/JuliaBinaryWrappers/Diamond_jll.jl/releases/download/Diamond-v2.1.8+0/Diamond.v2.1.8.x86_64-linux-musl-cxx11.tar.gz"
[[Diamond]]
arch = "x86_64"
git-tree-sha1 = "99ba4327ca0965d68f374ae0f05512730a0e971e"
os = "freebsd"

    [[Diamond.download]]
    sha256 = "1456b933e880b0e062d2d53abbc2d6f62a828e99395b34b25ada76abd7cab4b2"
    url = "https://github.com/JuliaBinaryWrappers/Diamond_jll.jl/releases/download/Diamond-v2.1.8+0/Diamond.v2.1.8.x86_64-unknown-freebsd.tar.gz"
