[[Diamond]]
arch = "aarch64"
git-tree-sha1 = "e19366de665e81d3e41c374e0c9f046fcedbb49e"
os = "macos"

    [[Diamond.download]]
    sha256 = "d0a75518ed62c02fee1bdde2be21ee7c2edc8d31d3fa9fecdeb4e79388d514fa"
    url = "https://github.com/JuliaBinaryWrappers/Diamond_jll.jl/releases/download/Diamond-v2.1.7+0/Diamond.v2.1.7.aarch64-apple-darwin.tar.gz"
[[Diamond]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3972ac238b7aaffa054e7f24004876f5a56e5e5c"
libc = "glibc"
os = "linux"

    [[Diamond.download]]
    sha256 = "74b71a600bfbcdc4ebb19a2aefe847103ac4fea7ec4c2aa6c6249615a2a643b9"
    url = "https://github.com/JuliaBinaryWrappers/Diamond_jll.jl/releases/download/Diamond-v2.1.7+0/Diamond.v2.1.7.aarch64-linux-gnu-cxx03.tar.gz"
[[Diamond]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c2d81b284d782ec2f1341c2e6f21a9a352a4684e"
libc = "glibc"
os = "linux"

    [[Diamond.download]]
    sha256 = "69751c71ad33b4a9edeaed72975538aed92c0bf4decfdd1a6abafbf013c62ce6"
    url = "https://github.com/JuliaBinaryWrappers/Diamond_jll.jl/releases/download/Diamond-v2.1.7+0/Diamond.v2.1.7.aarch64-linux-gnu-cxx11.tar.gz"
[[Diamond]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "59977c13f40afd6fdc1592e3ffb79a808c366d95"
libc = "musl"
os = "linux"

    [[Diamond.download]]
    sha256 = "5351c9f4b130bf3734154299f938c24319df70e0d42288e5d0b3955620c16c77"
    url = "https://github.com/JuliaBinaryWrappers/Diamond_jll.jl/releases/download/Diamond-v2.1.7+0/Diamond.v2.1.7.aarch64-linux-musl-cxx03.tar.gz"
[[Diamond]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "63cc249fee669cbec09437e754857720873cf435"
libc = "musl"
os = "linux"

    [[Diamond.download]]
    sha256 = "468ff23d53082eb4a5de2da53b1e429cd5f7532cc599d05f0ca07c368d5e9e9b"
    url = "https://github.com/JuliaBinaryWrappers/Diamond_jll.jl/releases/download/Diamond-v2.1.7+0/Diamond.v2.1.7.aarch64-linux-musl-cxx11.tar.gz"
[[Diamond]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "962ce40c6900c92fcf064f2a18a8f701b17e10f0"
libc = "glibc"
os = "linux"

    [[Diamond.download]]
    sha256 = "1b6610ab108596ffb206dd3baf122c219bffc3327c1b0bf2adbc3d82c20a3218"
    url = "https://github.com/JuliaBinaryWrappers/Diamond_jll.jl/releases/download/Diamond-v2.1.7+0/Diamond.v2.1.7.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Diamond]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6998fefdd70afb3118f3b81e885bbd63bd86bce8"
libc = "glibc"
os = "linux"

    [[Diamond.download]]
    sha256 = "754610a3b1dad6f5543d32e41ecbc742da11d8fa3653063d6f9d9c7ce31c20db"
    url = "https://github.com/JuliaBinaryWrappers/Diamond_jll.jl/releases/download/Diamond-v2.1.7+0/Diamond.v2.1.7.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Diamond]]
arch = "x86_64"
git-tree-sha1 = "8a7e74ecaf63a58e388e6d5a6cadd927f7f194c0"
os = "macos"

    [[Diamond.download]]
    sha256 = "7180c18438f14d3ef0370248d5e63084c1e979d041bb6bf4806826364bf1e9b4"
    url = "https://github.com/JuliaBinaryWrappers/Diamond_jll.jl/releases/download/Diamond-v2.1.7+0/Diamond.v2.1.7.x86_64-apple-darwin.tar.gz"
[[Diamond]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "79d64b65aefe467484600f8509c636a42e6fd1e3"
libc = "glibc"
os = "linux"

    [[Diamond.download]]
    sha256 = "ae2dd7ac6eae188c979ff3606eb9a548313f9e27f5c1716d87370eec6c3610ef"
    url = "https://github.com/JuliaBinaryWrappers/Diamond_jll.jl/releases/download/Diamond-v2.1.7+0/Diamond.v2.1.7.x86_64-linux-gnu-cxx03.tar.gz"
[[Diamond]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "018db71d5b00c542c661c6e605d2f3468601a710"
libc = "glibc"
os = "linux"

    [[Diamond.download]]
    sha256 = "98bac3fbe504e32bbbb1cf91af21594afa74060f779fa31e369322ccd10d197b"
    url = "https://github.com/JuliaBinaryWrappers/Diamond_jll.jl/releases/download/Diamond-v2.1.7+0/Diamond.v2.1.7.x86_64-linux-gnu-cxx11.tar.gz"
[[Diamond]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "04ce1613e3581d44f10b6e41d63831f3af1c437b"
libc = "musl"
os = "linux"

    [[Diamond.download]]
    sha256 = "30c9da9ad0083eb870289689b59f36764d0b7d1f2868063fcf902d4cdc9a4b02"
    url = "https://github.com/JuliaBinaryWrappers/Diamond_jll.jl/releases/download/Diamond-v2.1.7+0/Diamond.v2.1.7.x86_64-linux-musl-cxx03.tar.gz"
[[Diamond]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dff843d13eaecd8e65e28138b9e6b9b868cfc3f0"
libc = "musl"
os = "linux"

    [[Diamond.download]]
    sha256 = "73fa66f81df4586720f2509ddefab224e8eb3de96c57732c3bfec88ada0f63be"
    url = "https://github.com/JuliaBinaryWrappers/Diamond_jll.jl/releases/download/Diamond-v2.1.7+0/Diamond.v2.1.7.x86_64-linux-musl-cxx11.tar.gz"
[[Diamond]]
arch = "x86_64"
git-tree-sha1 = "e1bdf3c6dac28817f3f1fbc043a93f26b6fd8e24"
os = "freebsd"

    [[Diamond.download]]
    sha256 = "3fa6f6003679849118fbc48ab243bab5bb1c6313fb1ca3af0bccf6f317b964e9"
    url = "https://github.com/JuliaBinaryWrappers/Diamond_jll.jl/releases/download/Diamond-v2.1.7+0/Diamond.v2.1.7.x86_64-unknown-freebsd.tar.gz"
